### ISSUE TITLE
Check that the only children of <dl> are <dt> and <dd>

### ISSUE THREAD

**Issue by jackdomleo7** [jackdomleo7/Checka11y.css#11]
To comply with valid HTML and correct HTML semantics, the direct children of a `<dl>` can **only** be `<dt>` and `<dd>`.

W3: https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html
MDN Docs: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

**Solution**

Maybe a selector like this may work:

```css
dl > *:not(dt):not(dd):after { ... }
```

**Comment by veerreshr** [comment]
Could I work on this issue ?

**Comment by jackdomleo7** [comment]
Absolutely!
