### ISSUE TITLE
Improve speed of tests

### ISSUE THREAD

**Issue by jackdomleo7** [jackdomleo7/Checka11y.css#117]
### Describe the new a11y feature or project enhancement

The Cypress tests can take up to 2 minutes to run, which uses up minutes and storage in the GitHub workflow. The tests are extremely simple, so can we find a way to make the tests a lot quicker? I.e. Could we change to Jest?

### Describe the solution you'd like

Tests to runner quicker. Anything is an improvement.

### Link(s)

- https://github.com/jackdomleo7/Checka11y.css/actions/workflows/Tests.yml

**Comment by jackdomleo7** [comment]
@Manishgupta200 just need to double-check with @tannerdolby whether he's ok with this since he said he might keep a look out for low hanging fruit while working on a related ticket.

If @tannerdolby is happy for you to take this ticket then I am too. Would be worth keep @tannerdolby in the loop though, because you'll both have tickets relating to the Cypress tests and I'd hope for any work to be duplicated or discarded due to recent changes.

**Comment by jackdomleo7** [comment]
Thank you for the breakdown @tannerdolby! I think my main concern is finding the fastest tool since I feel these tests are relatively simple.

**Comment by tannerdolby** [comment]
Your welcome @jackdomleo7! Yeah, agreed the test cases are simple so finding the most performant tool would be ideal. After researching a bit, I couldn't confidently declare a clear "performance" winner between the two. From my experience in MDN Web Docs and GoogleChrome repos, they are using Jest for testing. 

If we can find a definitive place that says "X is faster than Y" then I think we should go with that, Cypress does a good job here, but if we don't want the nice UI and only want unit tests (as the test cases are relatively simple to begin with), Jest "might" be slightly more performant. I just haven't found anything that puts it plainly and says Jest is faster than Cypress or vica-versa.

**Comment by jackdomleo7** [comment]
I think the Cypress UI is unnecessary here. We can probably integrate a UI diffing tool in Jest.

I'm happy with js-dom for a project like this, to be honest. I've used js-dom for years in other projects (mainly Vue) and not had any issues so I think for a small CSS project, js-dom will be fine. Would you agree?

That is a nice resource! Thanks for sharing.

**Comment by tannerdolby** [comment]
Ok will do :)

Fortunately for us there weren't very many changes to be made for updating Cypress from 6 to the latest version 8.7.0. In terms of performance improvements that I noticed, I'd say its safe to remove any looping using `.each()` for checking a single element in `index.html`. 

This occurs for the `accesskey` test and a few others, the majority of them benefit from using `.each()` as there are multiple elements needing to be asserted but removing each() for singular elements will yield small improvements as we don't add extra calls.

**Comment by jackdomleo7** [comment]
Thanks again @tannerdolby for the recent PR! @Manishgupta200, if you're still interested, if you can find any other ways that Tanner may have missed to improve the tests, I'd be happy for you to do so. No worries if not though 🙂

**Comment by Manishgupta200** [comment]
> Thanks again @tannerdolby for the recent PR! @Manishgupta200, if you're still interested, if you can find any other ways that Tanner may have missed to improve the tests, I'd be happy for you to do so. No worries if not though 🙂

Yaa, thanks for your appreciation
