### ISSUE TITLE
[ENHANCEMENT]: Generate minified CSS files too

### ISSUE THREAD

**Issue by jackdomleo7** [jackdomleo7/Checka11y.css#144]
# Project Enhancement or Maintenance Idea

## Describe the enhancement or maintenance

It'd be worth including an option to include a minified version of the Checka11y.css stylesheets as well as the expanded versions. Projects such as [Checka11y.css browser extension](https://github.com/jackdomleo7/Checka11y.css-browser-extension) would really benefit from the smaller file size stylesheets being available to use.

## Acceptance criteria

- [ ] In the build process, generate minified CSS stylesheets (`checka11y.min.css`, `checka11y-warnings.min.css`, `checka11y-errors.min.css`)
- [ ] Ensure the expanded stylesheets are still being generated
- [ ] Update README documentation

## Why is this enhancement or maintenance important?

It's no harm to also provide a minified version of the stylesheet, especially since the project is growing.

**Comment by tannerdolby** [comment]
👋 @jackdomleo7 I think this is a great idea and completely agree there is no harm in providing a minified stylesheet to give users the option.

I've used the npm package [`clean-css`](https://www.npmjs.com/package/clean-css) for minifying CSS in the past. Other options for minifying exist but this is just one I've enjoyed using for build-time minifications.

**Comment by jackdomleo7** [comment]
Ah nice! I've used cssnano in the past but I'm happy with any tool that does the job. I wasn't aware of clean-css though, it looks good, thank you.
