### ISSUE TITLE
Add links to 'Features' section in README

### ISSUE THREAD

**Issue by jackdomleo7** [jackdomleo7/Checka11y.css#17]
Would it be useful to add links to the list of features on the README as a form of validity?

**Comment by danspratling** [comment]
@jackdomleo7 What kind of links were you thinking of?

**Comment by jackdomleo7** [comment]
For example, in the README:

`- Missing alt attributes on images (https://www.w3.org/TR/UNDERSTANDING-WCAG20/meaning-doc-lang-id.html)`

Just as validity of the features we have and why we have them.

**Comment by danspratling** [comment]
I'm concerned with the readme becoming absolutely massive and unmanageable.

All the readme should cover (in my opinion) is
- What this is
- How to get set up
- How to contribute

Maybe we start putting together a documentation folder and have a references.md file which covers this for those who want to really dig into it?

**Comment by jackdomleo7** [comment]
That's a great idea.

- Created `/references.md` and add a link to it in the `README.md`
- Add links to official W3C docs (or other trusted source) for each feature

**Comment by shonamckenzie** [comment]
Hi @jackdomleo7 I'd like to look at this one if that's ok
