### ISSUE TITLE
Warn when media is set to autoplay

### ISSUE THREAD

**Issue by jackdomleo7** [jackdomleo7/Checka11y.css#18]
"Unexpected video and audio can be distracting and disruptive, especially for certain kinds of cognitive disability such as ADHD. Certain kinds of autoplaying video and animation can be a trigger for vestibular and seizure disorders." - The A11y Project.

Link: https://www.a11yproject.com/checklist/#make-sure-that-media-does-not-autoplay

**Proposed solution**

Check for when the `autoplay` attribute is used and provide a warning.

```css
[autoplay] {
  ...
}
```

**Comment by devindford** [comment]
Hey Jack! I would love to work on this issue, can you please assign me to it!

**Comment by jackdomleo7** [comment]
Of course! A little more research may be required 😊

**Comment by danspratling** [comment]
@jackdomleo7 @devindford were you not able to assign yourself? I've been working under the assumption that people can "pick up" issues by self-assigning, rather than having to ask me and jack to assign them to it directly.

**Comment by devindford** [comment]
I'll double check, I wasn't sure if that was a possibility

**Comment by devindford** [comment]
I've found that unless you are the owner or a collaborator on the project, you can not assign issues or even self assign them.

**Comment by jackdomleo7** [comment]
Thank you for double checking for us @devindford! 😊
