### ISSUE TITLE
Logo and icon wanted! Submit designs

### ISSUE THREAD

**Issue by jackdomleo7** [jackdomleo7/Checka11y.css#20]
We are looking for someone to design and donate Checka11y.css a logo and an icon.

**Design brief**

- Keep it simple (this is an accessibility tool, so it can't be complex)

Logo:

- Must include `Checka11y.css`
- Should reflect accessibility 🤷‍♂️
- Dimensions:
  - Rectangular
  - At least `1280px width by 640px height`

Icon:

- Should be able to easily relate to the logo
- Will be primarily used as the favicon on the website
- Dimensions:
  - Square
  - At least `500px by 500px`

We thank you in advance! 😊

---

If you have any designs, please submit below in the comments (or [message Jack on Twitter](https://twitter.com/jackdomleo7) or [message Jack on LinkedIn](https://linkedin.com/in/jackdomleo7)).

You will be credited for the design and added as a contributor (for this to happen, we will ask you to create a pull request adding the images to the repository).

**Comment by emmalearnscode** [comment]
Do you have any specific colours in mind?

**Comment by jackdomleo7** [comment]
I was thinking some simple like pure black & white 😊
