### ISSUE TITLE
Release to npm

### ISSUE THREAD

**Issue by jackdomleo7** [jackdomleo7/Checka11y.css#21]
This would be a good project to have published to npm with some good usage docs.

**Comment by jackdomleo7** [comment]
I'm working on this.

**Comment by Amansaxena001** [comment]
Lets work together on this what u say? release this ASAP

**Comment by jackdomleo7** [comment]
I'm not sure how that would work because it's just one command in the terminal from the owner of the repo. Anyway, I forgot to close this item when I published it about 3 hours ago. 🙂

**Comment by jackdomleo7** [comment]
Closing this as I have published the first version to npm - v1.0.0
