### ISSUE TITLE
Check the dir attribute has the correct values

### ISSUE THREAD

**Issue by jackdomleo7** [jackdomleo7/Checka11y.css#22]
The `dir` attribute can only have the values, `ltr`, `rtl` and `auto`.

Link: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir

**Proposed solution**

Throw an error if the `dir` attribute is anything other than `ltr`, `rtl` or `auto`.

```css
[dir]:not( [dir="rtl"] ):not( [dir="ltr"] ):not( [dir="auto"] ) {
  ...
}

[dir]:not( [dir="rtl"] ):not( [dir="ltr"] ):not( [dir="auto"] )::after {
  ...
}
```

**Comment by Being-Maverick** [comment]
Hey @jackdomleo7 , I will resolve this. Please assign it to me.

**Comment by jackdomleo7** [comment]
Sorry, I need to update the contributing guidelines. 1 issue per person at a time, unless you're a collaborator. Please complete #23 before doing this.

**Comment by Being-Maverick** [comment]
Sure.

**Comment by wulforr** [comment]
@jackdomleo7 can you assign it to me.
