### ISSUE TITLE
Missing keyword from some features in README

### ISSUE THREAD

**Issue by jackdomleo7** [jackdomleo7/Checka11y.css#23]
The below features in the README need to be refactored to use the `direct` keyword. This needs changing because almost anything can go within an `<li>`, `<dt>` and `<dd>`, but these can **only** be the direct children of `<ul>`, `<ol>` and `<dl>`.

```markdown
- Checks <li> is the only child of <ol> and <ul>
- Checks <dt> and <dd> are the only children of <dl>
```

**Proposed solution**

```markdown
- Checks <li> is the only direct child of <ol> and <ul>
- Checks <dt> and <dd> are the only direct children of <dl>
```

**Comment by Being-Maverick** [comment]
Hey @jackdomleo7 , I want to work on this. Please assign it to me.

**Comment by jackdomleo7** [comment]
Sure, if you wait until tomorrow to submit your pull request, you'll get a Hacktoberfest point 😊

**Comment by Being-Maverick** [comment]
Thanks.
