### ISSUE TITLE
test.html mentioned in CONTRIBUTING.md doesn't exist.

### ISSUE THREAD

**Issue by Being-Maverick** [jackdomleo7/Checka11y.css#27]
Within the Pull Request Process section, of the contributing guidelines, it is mentioned to update the test.html file, but it doesn't exist. It should be index.html, within the test directory, I suppose?

**Comment by wulforr** [comment]
@Being-Maverick good catch, it needs to be changed to index.html in test directory

**Comment by jackdomleo7** [comment]
Good spot! I originally had a `test.html` file, but moved it into its own directory.

For whoever picks this up, I'd like it changing to `test/index.html` rather than saying `index.html in the test directory`. 😊

**Comment by veerreshr** [comment]
Could I make these changes?
