### ISSUE TITLE
Buttons should not contain interactive content

### ISSUE THREAD

**Issue by alvaromontoro** [jackdomleo7/Checka11y.css#32]
### Describe the new a11y feature or project enhancement

A `<button>` tag should not contain interactive content. 

### Describe the solution you'd like

Following an approach similar to what is done for the `<a>` tag, show an error message when interactive content is present as a descendant of a button.

### Link(s)

- [W3C Specification for `<button>`](https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element)
- [MDN Docs: `<button>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)
- [MDN docs: list of interactive content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Interactive_content)

**Comment by jackdomleo7** [comment]
Love this! Do you have an idea of what elements should not go inside a `<button>`? I have a feeling it's going to be nearly exactly the same as `<a>`.

**Comment by alvaromontoro** [comment]
The list of elements is in the last link - [MDN docs: list of interactive content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Interactive_content):

> Interactive content includes elements that are specifically designed for user interaction. Elements that belong to this category include: `<a>`, `<button>`, `<details>`, `<embed>`, `<iframe>`, `<keygen>`, `<label>`, `<select>`, and `<textarea>`.
Some elements belong to this category only under specific conditions:
>
> - `<audio>`, if the `controls` attribute is present
> - `<img>`, if the `usemap` attribute is present
> - `<input>`, if the `type` attribute is not in the hidden state
> - `<menu>`, if the `type` attribute is in the toolbar state
> - `<object>`, if the `usemap` attribute is present
> - `<video>`, if the `controls` attribute is present

**Comment by cat-street** [comment]
I'd like to pick it up 🙂
