### ISSUE TITLE
Improve visibility on errors

### ISSUE THREAD

**Issue by danspratling** [jackdomleo7/Checka11y.css#4]
As an accessibility tool, there can't be any accessibility issues caused by the notification of error messages, but in its current state there are definitely some problems I can see.

Suggestions:
- Images have a grayscale filter applied, along with a border
- All borders are actually double-borders, with a light-red inner border and a dark-red outer border to ensure they are visible regardless of the content, theme, etc.
- Text-based content has a forced background applied as well as a border
- Errors which are text alone aren't nearly noticeable enough, so we should work on defining clear alert styles (something like https://getbootstrap.com/docs/4.5/components/alerts/)
- add warnings for less critical issues which may occur

**Comment by jackdomleo7** [comment]
These are good suggestions! I think we can look into this more and start working out what the best way to do _stuff_ is. 💪

**Comment by jackdomleo7** [comment]
Currently working on this in the branch `#4-improve-visibility-on-errors`

**Comment by wulforr** [comment]
Using after pseudo-element to display error message is also not visible for many elements such as img. We will need a way to display an error message for every element.

**Comment by danspratling** [comment]
@wulforr I noticed this too, but not sure how to approach this with purely css.

**Comment by jackdomleo7** [comment]
Me neither. I was hoping for a pure CSS tool, doing this would require JS and changes to the consumer's markup 😕

**Comment by wulforr** [comment]
@danspratling  @jackdomleo7 same here, If this is not possible we could try highlighting these elements more by changing opacity or background color.
This is the best that I can think of at the moment but this still does not solve of problem of not showing error message. It would give the user an idea that this element is wrong but not what is wrong in this element.

**Comment by jackdomleo7** [comment]
I think maybe, we should hold fire on this and get actual user feedback when I release the beta version. That will help us a lot and prevent us from jumping to conclusions. 😊
