### ISSUE TITLE
Add Cypress testing tool (and write tests)

### ISSUE THREAD

**Issue by alvaromontoro** [jackdomleo7/Checka11y.css#66]
### Describe the new a11y feature or project enhancement

This would be a project enhancement: adding a testing tool. Right now, all the checks to verify that the new change didn't affect anything already in place have to be done manually. This is error-prone (it's easy to miss something) and unsustainable in the long run, when many tests are reached.

### Describe the solution you'd like

My suggestion would be adding Cypress as the testing tool. Cypress is simple and easy, and as a test, I was able to get something up and running in 10 minutes:

<img width="1163" alt="screenshot of Cypress after running on Checka11y.css with 3 tests" src="https://user-images.githubusercontent.com/2205212/95816164-09b70c00-0ce4-11eb-9b73-a1e10eb0570d.png">

It will help run all the tests in an automated way, without missing anything. For each new feature, the developer would be in charge of writing the test for their feature and verify that the rest are still Ok (e.g. just run the tests and make sure all of them pass.)

### Link(s)

- [Cypress website](https://www.cypress.io/)
- [Cypress documentation](https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell)

**Comment by tricinel** [comment]
Ohhh...this would be really cool! I'd be more than happy to contribute as well!

**Comment by jackdomleo7** [comment]
This sounds really good! I have zero experience with Cypress 😅

**Comment by alvaromontoro** [comment]
@tricinel If you want, I could push what I have –I added some tests and a couple of functions to be able to read `::before` and `::after` styles– and you can continue or we can divide the work. I don't know if the structure I have is the best; it works, but it would need some review.

**Comment by tricinel** [comment]
Yeah, that'd be cool! I don't have that much experience with Cypress either - I'm looking forward to learning though. @alvaromontoro let's continue on your work if that's alright. 👍
