### ISSUE TITLE
Browser extension feature

### ISSUE THREAD

**Issue by kurtextrem** [jackdomleo7/Checka11y.css#80]
### Describe the new a11y feature or project enhancement

Would be great to use this as bookmark in the browser, then you can just click the bookmark whenever you wanna check the status.

### Describe the solution you'd like

Code:
```javascript
javascript:(function(){var a=document.createElement('link');a.rel='stylesheet';a.href='https://checka11y.jackdomleo.dev/css/checka11y.min.css';document.body.appendChild(a)})();
```

Feel free to add it to the website/readme or similar.

**Comment by jackdomleo7** [comment]
Hi thanks for this feedback! I think it's a great idea, but I've edited the title from being a bookmark to being a browser extension. 🙂
