### ISSUE TITLE
Update Cypress tests to test every feature

### ISSUE THREAD

**Issue by jackdomleo7** [jackdomleo7/Checka11y.css#86]
### Describe the new a11y feature or project enhancement

Cypress was implemented in #68, but only a few tests were created for a few features. We ideally need to test every feature.

### Describe the solution you'd like

Test the features.

### Link(s)

N/A

**Comment by alvaromontoro** [comment]
Need assistance with this?

**Comment by jackdomleo7** [comment]
@alvaromontoro You can do if you would like. I got as far as investigating running the tests on other browsers other than Chrome (but I bumped into some issues), then I had to move onto another project. My next plan was to make note of what exactly to test for, then I was going to write them. Unfortunately, I'm going to be on other projects for a few months.
