### ISSUE TITLE
Live Coding Review

### ISSUE THREAD

**Issue by David-Spudic** [jackdomleo7/Checka11y.css#9]
Looking at the project, **I was amazed how many features are already implemented**. However, I think I found one feature that would help the project to get to the next level. This is all about live coding.

## What do I mean by that?

By live coding I mean that it would be pretty cool if we as developers could see the bugs we are making while we are programming.

Since tools like W3C's are well established and do not offer such a feature, this would be a reason for many users to switch to this project.

##How to implement?

Since the website is not allowed to reload during such sessions, every single script would have to be modified during implementation. The method appendChild, makes it possible to reload a Javascript functionality without reloading the website itself. Here is a code example:

```
var s = document.createElement('script');
s.src = 'path/to/script-that-injects-data-or-NEW-widgets.js';
document.body.appendChild(s)
```

Now that we can reload the scripts which check if something is wrong without our script disappearing, there is only one thing missing.

_- Recognize when a user has typed something_

This is implemented quite simply. First you have to develop an IDE like front-end via HTML, where you can write your code later. With an ID you can validate HTML, CSS, Javascript etc. while typing, with a code structure like shown here as an example:

```
var inputBox = document.getElementById('codeinput');
var s = document.createElement('script');
s.src = 'path/to/script-that-injects-data-or-NEW-widgets.js';

inputBox.onkeyup = function(){
    document.body.appendChild(s)
}
```

Voilla :)

What do you think about it?

**Comment by danspratling** [comment]
I'm not entirely sure what you mean. This is a css based utility, which means once included errors will show up once the correct combination of tags/attributes appears.

If you're looking for something more programmatic which checks through the code you've written looking for more direct problems, content issues or similar then that's a problem reserved for other tools, like (eslint-plugin-jsx-a11y)[https://github.com/evcohen/eslint-plugin-jsx-a11y], and manual testing which automated tools could never entirely replace.

Let me know if I've misunderstood what you're suggesting.

**Comment by David-Spudic** [comment]
I think I caused some confusion with the examples of HTML etc. 

What I wanted to show with my above suggestion is that the program is currently (as I saw it, please correct me if I'm wrong) trimmed so that you always have to manually start the CSS "validator" when you make changes. 

But to give the user a more comfortable experience, you could automate this non-automated process. Thats what i wanted to say / suggest.

**Comment by jackdomleo7** [comment]
I think I understand what you're asking and I think it will already do this. As you're writing the code/HTML, the CSS automatically hooks onto whatever you're writing, you don't have to restart anything.

E.g. you could inspect this comment and start adding your own HTML and automatically, the GitHub stylesheets will apply the styles to whatever you've just written in the inspector.

I'm happy to leave this issue open if we've misunderstood, then you, @David-Spudic, can provide us with more details when we release it?

**Comment by danspratling** [comment]
Going to close this. I don't think this is in scope and it appears the author agrees (based on the emoji).

CSS is automatic so at most you'll have to refresh the page after making changes to see them applied.

In future, it might be worth considering a tool with auto-reload if we convert this to a different approach than testing directly in HTML/CSS files but for now that would be a bit much.
